import Foundation
import XCTest
@testable import IslamicKitPlus

// Loader and `Codable` models for the cross-language conformance fixtures
// generated by `tool/conformance/generate.dart` in the Dart package (see
// `conformance/README.md` there). Every fixture family has a test class in
// this directory that loops over each case and asserts equality against the
// Swift port.

enum ConformanceFixtures {
    /// Decodes `Fixtures/conformance/<name>.json` from the test bundle.
    static func load<T: Decodable>(_ name: String, as type: T.Type = T.self) throws -> T {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures/conformance"),
            "missing conformance fixture \(name).json"
        )
        return try JSONDecoder().decode(T.self, from: Data(contentsOf: url))
    }

    /// Parses the `yyyy-mm-dd` form the fixtures use for civil dates.
    static func date(_ iso: String) -> CivilDate {
        let parts = iso.split(separator: "-").map { Int($0)! }
        return CivilDate(year: parts[0], month: parts[1], day: parts[2])
    }

    /// Parses `yyyy-mm-ddThh:mm:ss`.
    static func dateTime(_ iso: String) -> CivilDateTime {
        let halves = iso.split(separator: "T")
        let d = date(String(halves[0]))
        let t = halves[1].split(separator: ":").map { Int($0)! }
        return CivilDateTime(date: d, hour: t[0], minute: t[1], second: t[2])
    }

    /// Parses the `dd-mm-yyyy` form the fixtures use for Hijri dates.
    static func dmy(_ s: String) -> (day: Int, month: Int, year: Int) {
        let p = s.split(separator: "-").map { Int($0)! }
        return (p[0], p[1], p[2])
    }
}

/// A raw-hours map as the generator emits it: prayer key -> hours, `null`
/// for an invalid time.
typealias FixtureRaw = [String: Double?]

/// The generator's `_methodParamsJson`.
struct FixtureMethodParams: Decodable {
    struct Adjustments: Decodable {
        let fajr, sunrise, dhuhr, asr, maghrib, isha: Int
    }

    struct Location: Decodable {
        let lat, lng: Double
    }

    let fajrAngle: Double
    let ishaAngle: Double?
    let ishaMinutesAfterMaghrib: Int?
    let ramadanIshaMinutesAfterMaghrib: Int?
    let maghribAngle: Double?
    let maghribMinutesAfterSunset: Int?
    let adjustments: Adjustments
    let midnightMode: String?
    let location: Location?

    func toMethodParams() -> MethodParams {
        MethodParams(
            fajrAngle: fajrAngle,
            ishaAngle: ishaAngle,
            ishaMinutesAfterMaghrib: ishaMinutesAfterMaghrib,
            ramadanIshaMinutesAfterMaghrib: ramadanIshaMinutesAfterMaghrib,
            maghribAngle: maghribAngle,
            maghribMinutesAfterSunset: maghribMinutesAfterSunset,
            adjustments: MethodAdjustments(
                fajr: adjustments.fajr, sunrise: adjustments.sunrise, dhuhr: adjustments.dhuhr,
                asr: adjustments.asr, maghrib: adjustments.maghrib, isha: adjustments.isha
            ),
            midnightMode: midnightMode.map(FixtureParams.midnightMode),
            location: location.map { Coordinates($0.lat, $0.lng) }
        )
    }
}

/// The generator's `_paramsJson`: every `CalculationParameters` field.
struct FixtureParams: Decodable {
    let method: String
    let customMethod: FixtureMethodParams?
    let school: String
    let asrShadowFactor: Double?
    let midnightMode: String?
    let highLatitudeRule: String
    let utcOffsetSeconds: Int
    let elevation: Double
    let shafaq: String
    let tune: String
    let imsakMinutes: Int
    let dhuhrMinutes: Int
    let calendarMethod: String
    let timezoneName: String?

    static func midnightMode(_ metaValue: String) -> MidnightMode {
        MidnightMode.allCases.first { $0.metaValue == metaValue }!
    }

    func toCalculationParameters() -> CalculationParameters {
        CalculationParameters(
            method: CalculationMethod.allCases.first { $0.code == method }!,
            customMethod: customMethod?.toMethodParams(),
            school: AsrSchool.allCases.first { $0.metaValue == school }!,
            asrShadowFactor: asrShadowFactor,
            midnightMode: midnightMode.map(FixtureParams.midnightMode),
            highLatitudeRule: HighLatitudeRule.allCases.first { $0.metaValue == highLatitudeRule }!,
            utcOffset: UTCOffset(seconds: utcOffsetSeconds),
            elevation: elevation,
            shafaq: Shafaq.allCases.first { $0.code == shafaq }!,
            tune: Tune(csv: tune),
            imsakMinutes: imsakMinutes,
            dhuhrMinutes: dhuhrMinutes,
            calendarMethod: CalendarMethod.allCases.first { $0.code == calendarMethod }!,
            timezoneName: timezoneName
        )
    }
}

/// The generator's `_hijriJson` (also embedded in `timings_detail` dates).
struct FixtureHijri: Decodable {
    let hijri: String
    let day: Int
    let month: Int
    let year: Int
    let monthLength: Int
    let weekdayEn: String
    let weekdayAr: String
    let monthEn: String
    let monthAr: String
    let holidays: [String]
}

// MARK: - Assertion helpers

/// Fails once per differing prayer, naming the case and the prayer.
func assertRawEqual(
    _ actual: RawPrayerTimes,
    _ expected: FixtureRaw,
    _ context: @autoclosure () -> String,
    file: StaticString = #filePath,
    line: UInt = #line
) {
    for prayer in Prayer.allCases {
        guard let slot = expected[prayer.key] else {
            XCTFail("\(context()): fixture lacks \(prayer.key)", file: file, line: line)
            continue
        }
        let got = actual[prayer]
        if got != slot {
            XCTFail(
                "\(context()): \(prayer.key) expected \(slot.map { "\($0)" } ?? "null") got \(got.map { "\($0)" } ?? "nil")",
                file: file, line: line
            )
        }
    }
}

/// `XCTAssertEqual` that only touches XCTest on a mismatch (the matrix has
/// tens of thousands of comparisons).
func assertSame<T: Equatable>(
    _ actual: T,
    _ expected: T,
    _ context: @autoclosure () -> String,
    file: StaticString = #filePath,
    line: UInt = #line
) {
    if actual != expected {
        XCTFail("\(context()): expected \(expected) got \(actual)", file: file, line: line)
    }
}

/// Compares two optional doubles within `accuracy`, treating `nil` as the
/// generator's `null` (a non-finite value).
func assertClose(
    _ actual: Double?,
    _ expected: Double?,
    accuracy: Double,
    _ context: @autoclosure () -> String,
    file: StaticString = #filePath,
    line: UInt = #line
) {
    switch (actual, expected) {
    case (nil, nil):
        return
    case let (a?, e?) where Swift.abs(a - e) <= accuracy:
        return
    default:
        XCTFail(
            "\(context()): expected \(expected.map { "\($0)" } ?? "null") got \(actual.map { "\($0)" } ?? "nil")",
            file: file, line: line
        )
    }
}

/// Asserts a `MethodParams` field by field against the fixture form.
func assertMethodParams(
    _ actual: MethodParams,
    _ expected: FixtureMethodParams,
    _ context: @autoclosure () -> String,
    file: StaticString = #filePath,
    line: UInt = #line
) {
    let c = context()
    assertSame(actual.fajrAngle, expected.fajrAngle, "\(c) fajrAngle", file: file, line: line)
    assertSame(actual.ishaAngle, expected.ishaAngle, "\(c) ishaAngle", file: file, line: line)
    assertSame(actual.ishaMinutesAfterMaghrib, expected.ishaMinutesAfterMaghrib, "\(c) ishaMinutesAfterMaghrib", file: file, line: line)
    assertSame(actual.ramadanIshaMinutesAfterMaghrib, expected.ramadanIshaMinutesAfterMaghrib, "\(c) ramadanIshaMinutesAfterMaghrib", file: file, line: line)
    assertSame(actual.maghribAngle, expected.maghribAngle, "\(c) maghribAngle", file: file, line: line)
    assertSame(actual.maghribMinutesAfterSunset, expected.maghribMinutesAfterSunset, "\(c) maghribMinutesAfterSunset", file: file, line: line)
    assertSame(actual.adjustments.fajr, expected.adjustments.fajr, "\(c) adjustments.fajr", file: file, line: line)
    assertSame(actual.adjustments.sunrise, expected.adjustments.sunrise, "\(c) adjustments.sunrise", file: file, line: line)
    assertSame(actual.adjustments.dhuhr, expected.adjustments.dhuhr, "\(c) adjustments.dhuhr", file: file, line: line)
    assertSame(actual.adjustments.asr, expected.adjustments.asr, "\(c) adjustments.asr", file: file, line: line)
    assertSame(actual.adjustments.maghrib, expected.adjustments.maghrib, "\(c) adjustments.maghrib", file: file, line: line)
    assertSame(actual.adjustments.isha, expected.adjustments.isha, "\(c) adjustments.isha", file: file, line: line)
    assertSame(actual.midnightMode?.metaValue, expected.midnightMode, "\(c) midnightMode", file: file, line: line)
    assertSame(actual.location?.latitude, expected.location?.lat, "\(c) location.lat", file: file, line: line)
    assertSame(actual.location?.longitude, expected.location?.lng, "\(c) location.lng", file: file, line: line)
}

/// Asserts a `HijriDate` against the fixture form.
func assertHijri(
    _ actual: HijriDate,
    _ expected: FixtureHijri,
    _ context: @autoclosure () -> String,
    file: StaticString = #filePath,
    line: UInt = #line
) {
    let c = context()
    assertSame(actual.formatted, expected.hijri, "\(c) hijri", file: file, line: line)
    assertSame(actual.day, expected.day, "\(c) day", file: file, line: line)
    assertSame(actual.month, expected.month, "\(c) month", file: file, line: line)
    assertSame(actual.year, expected.year, "\(c) year", file: file, line: line)
    assertSame(actual.monthLength, expected.monthLength, "\(c) monthLength", file: file, line: line)
    assertSame(actual.weekdayEn, expected.weekdayEn, "\(c) weekdayEn", file: file, line: line)
    assertSame(actual.weekdayAr, expected.weekdayAr, "\(c) weekdayAr", file: file, line: line)
    assertSame(actual.monthEn, expected.monthEn, "\(c) monthEn", file: file, line: line)
    assertSame(actual.monthAr, expected.monthAr, "\(c) monthAr", file: file, line: line)
    assertSame(actual.holidays, expected.holidays, "\(c) holidays", file: file, line: line)
}
