// Generated by islamic_kit_plus tool/generate_native_data.dart — DO NOT EDIT.
// Regenerate from the Dart package; every literal here mirrors the Dart source.

/// A localized (English + Arabic) name pair.
public struct LocalizedName: Hashable, Sendable {
    public let en: String
    public let ar: String

    public init(en: String, ar: String) {
        self.en = en
        self.ar = ar
    }
}

/// Static English/Arabic name tables for Gregorian and Hijri calendars.
///
/// Weekdays are keyed by ISO weekday number (Mon = 1 … Sun = 7).
public enum Localizer {
    /// Hijri months 1..12.
    public static let islamicMonths: [Int: LocalizedName] = [
        1: LocalizedName(en: "Muharram", ar: "مُحَرَّم"),
        2: LocalizedName(en: "Safar", ar: "صَفَر"),
        3: LocalizedName(en: "Rabi al-awwal", ar: "رَبيع الأوّل"),
        4: LocalizedName(en: "Rabi al-thani", ar: "رَبيع الثاني"),
        5: LocalizedName(en: "Jumadi al-awal", ar: "جُمادى الأول"),
        6: LocalizedName(en: "Jumadi al-akhir", ar: "جُمادى الآخر"),
        7: LocalizedName(en: "Rajab", ar: "رَجَب"),
        8: LocalizedName(en: "Sha'ban", ar: "شَعْبان"),
        9: LocalizedName(en: "Ramadan", ar: "رَمَضان"),
        10: LocalizedName(en: "Shawwal", ar: "شَوّال"),
        11: LocalizedName(en: "Dhu al-Qa'dah", ar: "ذوالقعدة"),
        12: LocalizedName(en: "Dhu al-Hijjah", ar: "ذوالحجة"),
    ]

    /// Hijri weekday names keyed by ISO weekday (Mon = 1 … Sun = 7).
    public static let hijriWeekdays: [Int: LocalizedName] = [
        1: LocalizedName(en: "Monday", ar: "الاثنين"),
        2: LocalizedName(en: "Tuesday", ar: "الثلاثاء"),
        3: LocalizedName(en: "Wednesday", ar: "الاربعاء"),
        4: LocalizedName(en: "Thursday", ar: "الخميس"),
        5: LocalizedName(en: "Friday", ar: "الجمعة"),
        6: LocalizedName(en: "Saturday", ar: "السبت"),
        7: LocalizedName(en: "Sunday", ar: "الاحد"),
    ]

    /// Gregorian months 1..12.
    public static let gregorianMonths: [Int: LocalizedName] = [
        1: LocalizedName(en: "January", ar: "يناير"),
        2: LocalizedName(en: "February", ar: "فبراير"),
        3: LocalizedName(en: "March", ar: "مارس"),
        4: LocalizedName(en: "April", ar: "أبريل"),
        5: LocalizedName(en: "May", ar: "مايو"),
        6: LocalizedName(en: "June", ar: "يونيو"),
        7: LocalizedName(en: "July", ar: "يوليو"),
        8: LocalizedName(en: "August", ar: "أغسطس"),
        9: LocalizedName(en: "September", ar: "سبتمبر"),
        10: LocalizedName(en: "October", ar: "أكتوبر"),
        11: LocalizedName(en: "November", ar: "نوفمبر"),
        12: LocalizedName(en: "December", ar: "ديسمبر"),
    ]

    /// Gregorian weekday names keyed by ISO weekday (Mon = 1 … Sun = 7).
    public static let gregorianWeekdays: [Int: LocalizedName] = [
        1: LocalizedName(en: "Monday", ar: "الإثنين"),
        2: LocalizedName(en: "Tuesday", ar: "الثلاثاء"),
        3: LocalizedName(en: "Wednesday", ar: "الأربعاء"),
        4: LocalizedName(en: "Thursday", ar: "الخميس"),
        5: LocalizedName(en: "Friday", ar: "الجمعة"),
        6: LocalizedName(en: "Saturday", ar: "السبت"),
        7: LocalizedName(en: "Sunday", ar: "الأحد"),
    ]

    /// English three-letter month abbreviations, index 0 = January.
    public static let monthAbbrEn: [String] = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

    /// Hijri weekday name for an ISO weekday (Mon = 1 … Sun = 7).
    public static func hijriWeekday(_ isoWeekday: Int) -> LocalizedName {
        hijriWeekdays[isoWeekday]!
    }

    /// Gregorian weekday name for an ISO weekday (Mon = 1 … Sun = 7).
    public static func gregorianWeekday(_ isoWeekday: Int) -> LocalizedName {
        gregorianWeekdays[isoWeekday]!
    }
}
