// Generated by islamic_kit_plus tool/generate_native_data.dart — DO NOT EDIT.
// Regenerate from the Dart package; every literal here mirrors the Dart source.

/// A curated city record: name, ISO-3166 alpha-2 country, optional state,
/// coordinates and the city's **standard-time** UTC offset in minutes.
public struct CityRecord: Hashable, Sendable {
    public let name: String
    public let country: String
    public let state: String?
    public let lat: Double
    public let lng: Double
    public let offsetMinutes: Int

    public init(name: String, country: String, state: String?, lat: Double, lng: Double, offsetMinutes: Int) {
        self.name = name
        self.country = country
        self.state = state
        self.lat = lat
        self.lng = lng
        self.offsetMinutes = offsetMinutes
    }
}

/// The curated, offline city set behind `BundledCityGeocoder`.
public enum CityDataset {
    /// 103 major world cities (capitals + large cities).
    public static let records: [CityRecord] = [
        CityRecord(name: "London", country: "GB", state: "England", lat: 51.5073509, lng: -0.1277583, offsetMinutes: 0),
        CityRecord(name: "Birmingham", country: "GB", state: "England", lat: 52.4862, lng: -1.8904, offsetMinutes: 0),
        CityRecord(name: "Manchester", country: "GB", state: "England", lat: 53.4808, lng: -2.2426, offsetMinutes: 0),
        CityRecord(name: "Dublin", country: "IE", state: nil, lat: 53.3498, lng: -6.2603, offsetMinutes: 0),
        CityRecord(name: "Paris", country: "FR", state: nil, lat: 48.856614, lng: 2.3522219, offsetMinutes: 60),
        CityRecord(name: "Marseille", country: "FR", state: nil, lat: 43.2965, lng: 5.3698, offsetMinutes: 60),
        CityRecord(name: "Madrid", country: "ES", state: nil, lat: 40.4168, lng: -3.7038, offsetMinutes: 60),
        CityRecord(name: "Barcelona", country: "ES", state: nil, lat: 41.3851, lng: 2.1734, offsetMinutes: 60),
        CityRecord(name: "Lisbon", country: "PT", state: nil, lat: 38.7223, lng: -9.1393, offsetMinutes: 0),
        CityRecord(name: "Rome", country: "IT", state: nil, lat: 41.9028, lng: 12.4964, offsetMinutes: 60),
        CityRecord(name: "Milan", country: "IT", state: nil, lat: 45.4642, lng: 9.19, offsetMinutes: 60),
        CityRecord(name: "Berlin", country: "DE", state: nil, lat: 52.52, lng: 13.405, offsetMinutes: 60),
        CityRecord(name: "Munich", country: "DE", state: nil, lat: 48.1351, lng: 11.582, offsetMinutes: 60),
        CityRecord(name: "Amsterdam", country: "NL", state: nil, lat: 52.3676, lng: 4.9041, offsetMinutes: 60),
        CityRecord(name: "Brussels", country: "BE", state: nil, lat: 50.8503, lng: 4.3517, offsetMinutes: 60),
        CityRecord(name: "Vienna", country: "AT", state: nil, lat: 48.2082, lng: 16.3738, offsetMinutes: 60),
        CityRecord(name: "Zurich", country: "CH", state: nil, lat: 47.3769, lng: 8.5417, offsetMinutes: 60),
        CityRecord(name: "Stockholm", country: "SE", state: nil, lat: 59.3293, lng: 18.0686, offsetMinutes: 60),
        CityRecord(name: "Oslo", country: "NO", state: nil, lat: 59.9139, lng: 10.7522, offsetMinutes: 60),
        CityRecord(name: "Copenhagen", country: "DK", state: nil, lat: 55.6761, lng: 12.5683, offsetMinutes: 60),
        CityRecord(name: "Warsaw", country: "PL", state: nil, lat: 52.2297, lng: 21.0122, offsetMinutes: 60),
        CityRecord(name: "Prague", country: "CZ", state: nil, lat: 50.0755, lng: 14.4378, offsetMinutes: 60),
        CityRecord(name: "Budapest", country: "HU", state: nil, lat: 47.4979, lng: 19.0402, offsetMinutes: 60),
        CityRecord(name: "Athens", country: "GR", state: nil, lat: 37.9838, lng: 23.7275, offsetMinutes: 120),
        CityRecord(name: "Bucharest", country: "RO", state: nil, lat: 44.4268, lng: 26.1025, offsetMinutes: 120),
        CityRecord(name: "Kyiv", country: "UA", state: nil, lat: 50.4501, lng: 30.5234, offsetMinutes: 120),
        CityRecord(name: "Moscow", country: "RU", state: nil, lat: 55.7558, lng: 37.6173, offsetMinutes: 180),
        CityRecord(name: "Istanbul", country: "TR", state: nil, lat: 41.0082, lng: 28.9784, offsetMinutes: 180),
        CityRecord(name: "Ankara", country: "TR", state: nil, lat: 39.9334, lng: 32.8597, offsetMinutes: 180),
        CityRecord(name: "Sarajevo", country: "BA", state: nil, lat: 43.8563, lng: 18.4131, offsetMinutes: 60),
        CityRecord(name: "Mecca", country: "SA", state: nil, lat: 21.3891, lng: 39.8579, offsetMinutes: 180),
        CityRecord(name: "Medina", country: "SA", state: nil, lat: 24.5247, lng: 39.5692, offsetMinutes: 180),
        CityRecord(name: "Riyadh", country: "SA", state: nil, lat: 24.7136, lng: 46.6753, offsetMinutes: 180),
        CityRecord(name: "Jeddah", country: "SA", state: nil, lat: 21.4858, lng: 39.1925, offsetMinutes: 180),
        CityRecord(name: "Dubai", country: "AE", state: nil, lat: 25.2048, lng: 55.2708, offsetMinutes: 240),
        CityRecord(name: "Abu Dhabi", country: "AE", state: nil, lat: 24.4539, lng: 54.3773, offsetMinutes: 240),
        CityRecord(name: "Doha", country: "QA", state: nil, lat: 25.2854, lng: 51.531, offsetMinutes: 180),
        CityRecord(name: "Kuwait City", country: "KW", state: nil, lat: 29.3759, lng: 47.9774, offsetMinutes: 180),
        CityRecord(name: "Manama", country: "BH", state: nil, lat: 26.2285, lng: 50.586, offsetMinutes: 180),
        CityRecord(name: "Muscat", country: "OM", state: nil, lat: 23.588, lng: 58.3829, offsetMinutes: 240),
        CityRecord(name: "Baghdad", country: "IQ", state: nil, lat: 33.3152, lng: 44.3661, offsetMinutes: 180),
        CityRecord(name: "Amman", country: "JO", state: nil, lat: 31.9454, lng: 35.9284, offsetMinutes: 120),
        CityRecord(name: "Jerusalem", country: "PS", state: nil, lat: 31.7683, lng: 35.2137, offsetMinutes: 120),
        CityRecord(name: "Beirut", country: "LB", state: nil, lat: 33.8938, lng: 35.5018, offsetMinutes: 120),
        CityRecord(name: "Damascus", country: "SY", state: nil, lat: 33.5138, lng: 36.2765, offsetMinutes: 120),
        CityRecord(name: "Cairo", country: "EG", state: nil, lat: 30.0444, lng: 31.2357, offsetMinutes: 120),
        CityRecord(name: "Alexandria", country: "EG", state: nil, lat: 31.2001, lng: 29.9187, offsetMinutes: 120),
        CityRecord(name: "Tripoli", country: "LY", state: nil, lat: 32.8872, lng: 13.1913, offsetMinutes: 120),
        CityRecord(name: "Tunis", country: "TN", state: nil, lat: 36.8065, lng: 10.1815, offsetMinutes: 60),
        CityRecord(name: "Algiers", country: "DZ", state: nil, lat: 36.7538, lng: 3.0588, offsetMinutes: 60),
        CityRecord(name: "Casablanca", country: "MA", state: nil, lat: 33.5731, lng: -7.5898, offsetMinutes: 60),
        CityRecord(name: "Rabat", country: "MA", state: nil, lat: 33.9716, lng: -6.8498, offsetMinutes: 60),
        CityRecord(name: "Tehran", country: "IR", state: nil, lat: 35.6892, lng: 51.389, offsetMinutes: 210),
        CityRecord(name: "Lagos", country: "NG", state: nil, lat: 6.5244, lng: 3.3792, offsetMinutes: 60),
        CityRecord(name: "Abuja", country: "NG", state: nil, lat: 9.0765, lng: 7.3986, offsetMinutes: 60),
        CityRecord(name: "Accra", country: "GH", state: nil, lat: 5.6037, lng: -0.187, offsetMinutes: 0),
        CityRecord(name: "Nairobi", country: "KE", state: nil, lat: -1.2921, lng: 36.8219, offsetMinutes: 180),
        CityRecord(name: "Addis Ababa", country: "ET", state: nil, lat: 9.03, lng: 38.74, offsetMinutes: 180),
        CityRecord(name: "Dar es Salaam", country: "TZ", state: nil, lat: -6.7924, lng: 39.2083, offsetMinutes: 180),
        CityRecord(name: "Khartoum", country: "SD", state: nil, lat: 15.5007, lng: 32.5599, offsetMinutes: 120),
        CityRecord(name: "Johannesburg", country: "ZA", state: nil, lat: -26.2041, lng: 28.0473, offsetMinutes: 120),
        CityRecord(name: "Cape Town", country: "ZA", state: nil, lat: -33.9249, lng: 18.4241, offsetMinutes: 120),
        CityRecord(name: "Dakar", country: "SN", state: nil, lat: 14.7167, lng: -17.4677, offsetMinutes: 0),
        CityRecord(name: "Karachi", country: "PK", state: nil, lat: 24.8607, lng: 67.0011, offsetMinutes: 300),
        CityRecord(name: "Lahore", country: "PK", state: nil, lat: 31.5204, lng: 74.3587, offsetMinutes: 300),
        CityRecord(name: "Islamabad", country: "PK", state: nil, lat: 33.6844, lng: 73.0479, offsetMinutes: 300),
        CityRecord(name: "Delhi", country: "IN", state: nil, lat: 28.7041, lng: 77.1025, offsetMinutes: 330),
        CityRecord(name: "Mumbai", country: "IN", state: nil, lat: 19.076, lng: 72.8777, offsetMinutes: 330),
        CityRecord(name: "Hyderabad", country: "IN", state: nil, lat: 17.385, lng: 78.4867, offsetMinutes: 330),
        CityRecord(name: "Dhaka", country: "BD", state: nil, lat: 23.8103, lng: 90.4125, offsetMinutes: 360),
        CityRecord(name: "Kabul", country: "AF", state: nil, lat: 34.5553, lng: 69.2075, offsetMinutes: 270),
        CityRecord(name: "Tashkent", country: "UZ", state: nil, lat: 41.2995, lng: 69.2401, offsetMinutes: 300),
        CityRecord(name: "Colombo", country: "LK", state: nil, lat: 6.9271, lng: 79.8612, offsetMinutes: 330),
        CityRecord(name: "Jakarta", country: "ID", state: nil, lat: -6.2088, lng: 106.8456, offsetMinutes: 420),
        CityRecord(name: "Surabaya", country: "ID", state: nil, lat: -7.2575, lng: 112.7521, offsetMinutes: 420),
        CityRecord(name: "Kuala Lumpur", country: "MY", state: nil, lat: 3.139, lng: 101.6869, offsetMinutes: 480),
        CityRecord(name: "Singapore", country: "SG", state: nil, lat: 1.352083, lng: 103.819836, offsetMinutes: 480),
        CityRecord(name: "Bangkok", country: "TH", state: nil, lat: 13.7563, lng: 100.5018, offsetMinutes: 420),
        CityRecord(name: "Manila", country: "PH", state: nil, lat: 14.5995, lng: 120.9842, offsetMinutes: 480),
        CityRecord(name: "Hanoi", country: "VN", state: nil, lat: 21.0278, lng: 105.8342, offsetMinutes: 420),
        CityRecord(name: "Beijing", country: "CN", state: nil, lat: 39.9042, lng: 116.4074, offsetMinutes: 480),
        CityRecord(name: "Shanghai", country: "CN", state: nil, lat: 31.2304, lng: 121.4737, offsetMinutes: 480),
        CityRecord(name: "Hong Kong", country: "HK", state: nil, lat: 22.3193, lng: 114.1694, offsetMinutes: 480),
        CityRecord(name: "Tokyo", country: "JP", state: nil, lat: 35.6762, lng: 139.6503, offsetMinutes: 540),
        CityRecord(name: "Seoul", country: "KR", state: nil, lat: 37.5665, lng: 126.978, offsetMinutes: 540),
        CityRecord(name: "Sydney", country: "AU", state: "New South Wales", lat: -33.8688, lng: 151.2093, offsetMinutes: 600),
        CityRecord(name: "Melbourne", country: "AU", state: "Victoria", lat: -37.8136, lng: 144.9631, offsetMinutes: 600),
        CityRecord(name: "Perth", country: "AU", state: "Western Australia", lat: -31.9523, lng: 115.8613, offsetMinutes: 480),
        CityRecord(name: "Auckland", country: "NZ", state: nil, lat: -36.8485, lng: 174.7633, offsetMinutes: 720),
        CityRecord(name: "New York", country: "US", state: "New York", lat: 40.7128, lng: -74.006, offsetMinutes: -300),
        CityRecord(name: "Chicago", country: "US", state: "Illinois", lat: 41.8781, lng: -87.6298, offsetMinutes: -360),
        CityRecord(name: "Houston", country: "US", state: "Texas", lat: 29.7604, lng: -95.3698, offsetMinutes: -360),
        CityRecord(name: "Denver", country: "US", state: "Colorado", lat: 39.7392, lng: -104.9903, offsetMinutes: -420),
        CityRecord(name: "Los Angeles", country: "US", state: "California", lat: 34.0522, lng: -118.2437, offsetMinutes: -480),
        CityRecord(name: "Toronto", country: "CA", state: "Ontario", lat: 43.6532, lng: -79.3832, offsetMinutes: -300),
        CityRecord(name: "Vancouver", country: "CA", state: "British Columbia", lat: 49.2827, lng: -123.1207, offsetMinutes: -480),
        CityRecord(name: "Mexico City", country: "MX", state: nil, lat: 19.4326, lng: -99.1332, offsetMinutes: -360),
        CityRecord(name: "Sao Paulo", country: "BR", state: nil, lat: -23.5505, lng: -46.6333, offsetMinutes: -180),
        CityRecord(name: "Rio de Janeiro", country: "BR", state: nil, lat: -22.9068, lng: -43.1729, offsetMinutes: -180),
        CityRecord(name: "Buenos Aires", country: "AR", state: nil, lat: -34.6037, lng: -58.3816, offsetMinutes: -180),
        CityRecord(name: "Bogota", country: "CO", state: nil, lat: 4.711, lng: -74.0721, offsetMinutes: -300),
        CityRecord(name: "Lima", country: "PE", state: nil, lat: -12.0464, lng: -77.0428, offsetMinutes: -300),
        CityRecord(name: "Santiago", country: "CL", state: nil, lat: -33.4489, lng: -70.6693, offsetMinutes: -240),
    ]

    /// Lower-case common country names -> ISO-3166 alpha-2 codes.
    public static let countryAliases: [String: String] = [
        "united kingdom": "GB",
        "great britain": "GB",
        "uk": "GB",
        "england": "GB",
        "united states": "US",
        "united states of america": "US",
        "usa": "US",
        "america": "US",
        "united arab emirates": "AE",
        "uae": "AE",
        "saudi arabia": "SA",
        "ksa": "SA",
        "egypt": "EG",
        "turkey": "TR",
        "türkiye": "TR",
        "india": "IN",
        "pakistan": "PK",
        "indonesia": "ID",
        "malaysia": "MY",
        "france": "FR",
        "germany": "DE",
        "canada": "CA",
        "australia": "AU",
    ]
}
