// Generated by islamic_kit_plus tool/generate_native_data.dart — DO NOT EDIT.
// Regenerate from the Dart package; every literal here mirrors the Dart source.

/// A prayer-time calculation method (twilight authority).
///
/// Each method carries its numeric `id` (the raw value) and short `code`, a
/// human-readable `methodName`, and its strongly-typed `params`. Methods with
/// ids 1–23 keep the numbering of the aladhan API; the regional authorities
/// aladhan does not publish are numbered from 101 so the id spaces never
/// collide. Cases are declared in the Dart package's order, so `allCases`
/// matches `CalculationMethod.values`.
public enum CalculationMethod: Int, CaseIterable, Sendable {
    case karachi = 1
    case isna = 2
    case mwl = 3
    case makkah = 4
    case egypt = 5
    case tehran = 7
    case gulf = 8
    case kuwait = 9
    case qatar = 10
    case singapore = 11
    case france = 12
    case turkey = 13
    case russia = 14
    case moonsighting = 15
    case dubai = 16
    case jakim = 17
    case tunisia = 18
    case algeria = 19
    case kemenag = 20
    case morocco = 21
    case portugal = 22
    case jordan = 23
    case oman = 101
    case munich = 102
    case maldives = 103
    case canada = 104
    case tajikistan = 105
    case vienna = 106
    case belgium = 107
    case sudan = 108
    case libya = 109
    case iraq = 110
    case luxembourg = 111
    case custom = 99

    /// Numeric id (aladhan id for ids <= 99).
    public var id: Int { rawValue }

    /// Short upper-case code, e.g. `"MWL"`.
    public var code: String { descriptor.code }

    /// Human-readable authority name.
    public var methodName: String { descriptor.methodName }

    /// The method's twilight parameters and published corrections.
    public var params: MethodParams { descriptor.params }

    /// Whether Fajr/Isha are bounded by the Moonsighting Committee twilight.
    public var usesMoonsighting: Bool { descriptor.usesMoonsighting }

    /// Whether `id` is an aladhan method id (ids above 99 are package extensions).
    public var isAladhanMethod: Bool { id <= 99 }

    /// Looks a method up by id, falling back to `.mwl`.
    public static func fromId(_ id: Int) -> CalculationMethod {
        CalculationMethod(rawValue: id) ?? .mwl
    }

    /// Looks a method up by code, falling back to `.mwl`.
    public static func fromCode(_ code: String) -> CalculationMethod {
        allCases.first { $0.code == code } ?? .mwl
    }

    /// Short UI label for `language`.
    public func title(_ language: Language) -> String {
        switch self {
        case .karachi: return language == .ar ? "كراتشي" : "Karachi"
        case .isna: return language == .ar ? "الجمعية الإسلامية لأمريكا الشمالية" : "ISNA"
        case .mwl: return language == .ar ? "رابطة العالم الإسلامي" : "Muslim World League"
        case .makkah: return language == .ar ? "أم القرى" : "Umm al-Qura"
        case .egypt: return language == .ar ? "مصر" : "Egypt"
        case .tehran: return language == .ar ? "طهران" : "Tehran"
        case .gulf: return language == .ar ? "منطقة الخليج" : "Gulf Region"
        case .kuwait: return language == .ar ? "الكويت" : "Kuwait"
        case .qatar: return language == .ar ? "قطر" : "Qatar"
        case .singapore: return language == .ar ? "سنغافورة" : "Singapore (MUIS)"
        case .france: return language == .ar ? "فرنسا" : "France (UOIF)"
        case .turkey: return language == .ar ? "تركيا (ديانت)" : "Turkey (Diyanet)"
        case .russia: return language == .ar ? "روسيا" : "Russia"
        case .moonsighting: return language == .ar ? "لجنة رؤية الهلال" : "Moonsighting Committee"
        case .dubai: return language == .ar ? "دبي" : "Dubai"
        case .jakim: return language == .ar ? "ماليزيا (جاكيم)" : "Malaysia (JAKIM)"
        case .tunisia: return language == .ar ? "تونس" : "Tunisia"
        case .algeria: return language == .ar ? "الجزائر" : "Algeria"
        case .kemenag: return language == .ar ? "إندونيسيا (كيمناغ)" : "Indonesia (Kemenag)"
        case .morocco: return language == .ar ? "المغرب" : "Morocco"
        case .portugal: return language == .ar ? "البرتغال" : "Portugal"
        case .jordan: return language == .ar ? "الأردن" : "Jordan"
        case .oman: return language == .ar ? "عُمان" : "Oman"
        case .munich: return language == .ar ? "ألمانيا (ميونخ)" : "Germany (Munich)"
        case .maldives: return language == .ar ? "المالديف" : "Maldives"
        case .canada: return language == .ar ? "كندا" : "Canada"
        case .tajikistan: return language == .ar ? "طاجيكستان" : "Tajikistan"
        case .vienna: return language == .ar ? "النمسا (فيينا)" : "Austria (Vienna)"
        case .belgium: return language == .ar ? "بلجيكا" : "Belgium"
        case .sudan: return language == .ar ? "السودان" : "Sudan"
        case .libya: return language == .ar ? "ليبيا" : "Libya"
        case .iraq: return language == .ar ? "العراق" : "Iraq"
        case .luxembourg: return language == .ar ? "لوكسمبورغ" : "Luxembourg"
        case .custom: return language == .ar ? "مخصّص" : "Custom"
        }
    }

    /// One-sentence description for `language`.
    public func description(_ language: Language) -> String {
        switch self {
        case .karachi: return language == .ar ? "جامعة العلوم الإسلامية بكراتشي — زاوية 18° لكل من الفجر والعشاء." : "University of Islamic Sciences, Karachi — 18° for both Fajr and Isha."
        case .isna: return language == .ar ? "الجمعية الإسلامية لأمريكا الشمالية — زاوية 15° لكل من الفجر والعشاء." : "Islamic Society of North America — 15° for both Fajr and Isha."
        case .mwl: return language == .ar ? "رابطة العالم الإسلامي — زاوية فجر 18° وعشاء 17°، وهي شائعة في أوروبا وغيرها." : "Muslim World League — 18° Fajr and 17° Isha, widely used across Europe and beyond."
        case .makkah: return language == .ar ? "جامعة أم القرى بمكة — زاوية فجر 18.5° مع تحديد العشاء بعد 90 دقيقة من المغرب (120 دقيقة في رمضان)." : "Umm Al-Qura University, Makkah — 18.5° Fajr with Isha fixed at 90 minutes after Maghrib (120 minutes during Ramadan)."
        case .egypt: return language == .ar ? "الهيئة المصرية العامة للمساحة — زاوية فجر 19.5° وعشاء 17.5°." : "Egyptian General Authority of Survey — 19.5° Fajr and 17.5° Isha."
        case .tehran: return language == .ar ? "معهد الجيوفيزياء بجامعة طهران — زاوية فجر 17.7° وعشاء 14° مع زاوية مغرب 4.5°." : "Institute of Geophysics, University of Tehran — 17.7° Fajr and 14° Isha with a 4.5° Maghrib angle."
        case .gulf: return language == .ar ? "منطقة الخليج — زاوية فجر 19.5° مع تحديد العشاء بعد 90 دقيقة من المغرب." : "Gulf Region — 19.5° Fajr with Isha fixed at 90 minutes after Maghrib."
        case .kuwait: return language == .ar ? "الكويت — زاوية فجر 18° وعشاء 17.5°." : "Kuwait — 18° Fajr and 17.5° Isha."
        case .qatar: return language == .ar ? "قطر — زاوية فجر 18° مع تحديد العشاء بعد 90 دقيقة من المغرب." : "Qatar — 18° Fajr with Isha fixed at 90 minutes after Maghrib."
        case .singapore: return language == .ar ? "المجلس الإسلامي في سنغافورة — زاوية فجر 20° وعشاء 18°." : "Majlis Ugama Islam Singapura — 20° Fajr and 18° Isha."
        case .france: return language == .ar ? "اتحاد المنظمات الإسلامية في فرنسا — زاوية 12° لكل من الفجر والعشاء." : "Union des Organisations Islamiques de France — 12° for both Fajr and Isha."
        case .turkey: return language == .ar ? "رئاسة الشؤون الدينية التركية (ديانت) — زاوية فجر 18° وعشاء 17°." : "Diyanet İşleri Başkanlığı, Turkey — 18° Fajr and 17° Isha."
        case .russia: return language == .ar ? "الإدارة الدينية لمسلمي روسيا — زاوية فجر 16° وعشاء 15°." : "Spiritual Administration of Muslims of Russia — 16° Fajr and 15° Isha."
        case .moonsighting: return language == .ar ? "لجنة رؤية الهلال العالمية — زاوية 18° للفجر والعشاء مقيّدة بحساب موسمي يتغيّر مع خط العرض والفصل." : "Moonsighting Committee Worldwide — 18° Fajr and Isha bounded by a seasonal calculation that varies with latitude and time of year."
        case .dubai: return language == .ar ? "دبي — زاوية 18.2° لكل من الفجر والعشاء." : "Dubai — 18.2° for both Fajr and Isha."
        case .jakim: return language == .ar ? "دائرة التنمية الإسلامية الماليزية (جاكيم) — زاوية فجر 20° وعشاء 18°." : "Jabatan Kemajuan Islam Malaysia (JAKIM) — 20° Fajr and 18° Isha."
        case .tunisia: return language == .ar ? "تونس — زاوية 18° لكل من الفجر والعشاء." : "Tunisia — 18° for both Fajr and Isha."
        case .algeria: return language == .ar ? "الجزائر — زاوية فجر 18° وعشاء 17°." : "Algeria — 18° Fajr and 17° Isha."
        case .kemenag: return language == .ar ? "وزارة الشؤون الدينية بجمهورية إندونيسيا — زاوية فجر 20° وعشاء 18°." : "Kementerian Agama Republik Indonesia — 20° Fajr and 18° Isha."
        case .morocco: return language == .ar ? "المملكة المغربية — زاوية فجر 18° وعشاء 17°." : "Morocco — 18° Fajr and 17° Isha."
        case .portugal: return language == .ar ? "الجالية الإسلامية في لشبونة — زاوية فجر 18° مع تحديد العشاء بعد 77 دقيقة من المغرب." : "Comunidade Islâmica de Lisboa — 18° Fajr with Isha fixed at 77 minutes after Maghrib."
        case .jordan: return language == .ar ? "وزارة الأوقاف والشؤون والمقدسات الإسلامية بالأردن — زاوية فجر 18.5° مع تحديد العشاء بعد 90 دقيقة من المغرب." : "Ministry of Awqaf, Islamic Affairs and Holy Places, Jordan — 18.5° Fajr with Isha fixed at 90 minutes after Maghrib."
        case .oman: return language == .ar ? "وزارة الأوقاف والشؤون الدينية بسلطنة عُمان — زاوية فجر 18.5° مع تحديد العشاء بعد 90 دقيقة من المغرب." : "Ministry of Endowments and Religious Affairs, Oman — 18.5° Fajr with Isha fixed at 90 minutes after Maghrib."
        case .munich: return language == .ar ? "المركز الإسلامي في ميونخ بألمانيا — زاوية فجر 18° وعشاء 17°." : "Islamic Center of Munich, Germany — 18° Fajr and 17° Isha."
        case .maldives: return language == .ar ? "وزارة الشؤون الإسلامية بجمهورية المالديف — زاوية فجر 18° وعشاء 17°." : "Ministry of Islamic Affairs, Maldives — 18° Fajr and 17° Isha."
        case .canada: return language == .ar ? "كندا — زاوية 15° لكل من الفجر والعشاء." : "Canada — 15° for both Fajr and Isha."
        case .tajikistan: return language == .ar ? "المركز الإسلامي في طاجيكستان — زاوية فجر 18° وعشاء 17°." : "Islamic Center of Tajikistan — 18° Fajr and 17° Isha."
        case .vienna: return language == .ar ? "الهيئة الإسلامية في النمسا بفيينا — زاوية فجر 18° وعشاء 17°." : "Islamic Community of Austria, Vienna — 18° Fajr and 17° Isha."
        case .belgium: return language == .ar ? "بلجيكا — زاوية فجر 18° وعشاء 17°." : "Belgium — 18° Fajr and 17° Isha."
        case .sudan: return language == .ar ? "السودان — زاوية فجر 19.5° وعشاء 17.5°." : "Sudan — 19.5° Fajr and 17.5° Isha."
        case .libya: return language == .ar ? "ليبيا — زاوية فجر 19.5° وعشاء 17.5°." : "Libya — 19.5° Fajr and 17.5° Isha."
        case .iraq: return language == .ar ? "العراق — زاوية فجر 18° وعشاء 17°." : "Iraq — 18° Fajr and 17° Isha."
        case .luxembourg: return language == .ar ? "لوكسمبورغ — زاوية فجر 18° وعشاء 17°." : "Luxembourg — 18° Fajr and 17° Isha."
        case .custom: return language == .ar ? "طريقة مخصّصة يوفّرها المستخدم بمعاملات الشفق الخاصة به." : "A user-supplied method that uses your own twilight parameters."
        }
    }

    private var descriptor: MethodDescriptor { Self.descriptors[self]! }

    private static let descriptors: [CalculationMethod: MethodDescriptor] =
        Dictionary(uniqueKeysWithValues: allCases.map { ($0, makeDescriptor($0)) })

    // One statement per case keeps type-checking linear.
    private static func makeDescriptor(_ method: CalculationMethod) -> MethodDescriptor {
        switch method {
        case .karachi:
            return MethodDescriptor(
                code: "KARACHI",
                methodName: "University of Islamic Sciences, Karachi",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 18.0, adjustments: MethodAdjustments(dhuhr: 1), location: Coordinates(24.8614622, 67.0099388)),
                usesMoonsighting: false)
        case .isna:
            return MethodDescriptor(
                code: "ISNA",
                methodName: "Islamic Society of North America (ISNA)",
                params: MethodParams(fajrAngle: 15.0, ishaAngle: 15.0, adjustments: MethodAdjustments(dhuhr: 1), location: Coordinates(39.70421229999999, -86.39943869999999)),
                usesMoonsighting: false)
        case .mwl:
            return MethodDescriptor(
                code: "MWL",
                methodName: "Muslim World League",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.0, adjustments: MethodAdjustments(dhuhr: 1), location: Coordinates(51.5194682, -0.1360365)),
                usesMoonsighting: false)
        case .makkah:
            return MethodDescriptor(
                code: "MAKKAH",
                methodName: "Umm Al-Qura University, Makkah",
                params: MethodParams(fajrAngle: 18.5, ishaMinutesAfterMaghrib: 90, ramadanIshaMinutesAfterMaghrib: 120, location: Coordinates(21.3890824, 39.8579118)),
                usesMoonsighting: false)
        case .egypt:
            return MethodDescriptor(
                code: "EGYPT",
                methodName: "Egyptian General Authority of Survey",
                params: MethodParams(fajrAngle: 19.5, ishaAngle: 17.5, adjustments: MethodAdjustments(dhuhr: 1), location: Coordinates(30.0444196, 31.2357116)),
                usesMoonsighting: false)
        case .tehran:
            return MethodDescriptor(
                code: "TEHRAN",
                methodName: "Institute of Geophysics, University of Tehran",
                params: MethodParams(fajrAngle: 17.7, ishaAngle: 14.0, maghribAngle: 4.5, midnightMode: .jafari, location: Coordinates(35.6891975, 51.3889736)),
                usesMoonsighting: false)
        case .gulf:
            return MethodDescriptor(
                code: "GULF",
                methodName: "Gulf Region",
                params: MethodParams(fajrAngle: 19.5, ishaMinutesAfterMaghrib: 90, location: Coordinates(24.1323638, 53.3199527)),
                usesMoonsighting: false)
        case .kuwait:
            return MethodDescriptor(
                code: "KUWAIT",
                methodName: "Kuwait",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.5, location: Coordinates(29.375859, 47.9774052)),
                usesMoonsighting: false)
        case .qatar:
            return MethodDescriptor(
                code: "QATAR",
                methodName: "Qatar",
                params: MethodParams(fajrAngle: 18.0, ishaMinutesAfterMaghrib: 90, location: Coordinates(25.2854473, 51.5310398)),
                usesMoonsighting: false)
        case .singapore:
            return MethodDescriptor(
                code: "SINGAPORE",
                methodName: "Majlis Ugama Islam Singapura, Singapore",
                params: MethodParams(fajrAngle: 20.0, ishaAngle: 18.0, adjustments: MethodAdjustments(dhuhr: 1), location: Coordinates(1.352083, 103.819836)),
                usesMoonsighting: false)
        case .france:
            return MethodDescriptor(
                code: "FRANCE",
                methodName: "Union Organization Islamic de France",
                params: MethodParams(fajrAngle: 12.0, ishaAngle: 12.0, location: Coordinates(48.856614, 2.3522219)),
                usesMoonsighting: false)
        case .turkey:
            return MethodDescriptor(
                code: "TURKEY",
                methodName: "Diyanet İşleri Başkanlığı, Turkey",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.0, location: Coordinates(39.9333635, 32.8597419)),
                usesMoonsighting: false)
        case .russia:
            return MethodDescriptor(
                code: "RUSSIA",
                methodName: "Spiritual Administration of Muslims of Russia",
                params: MethodParams(fajrAngle: 16.0, ishaAngle: 15.0, location: Coordinates(54.73479099999999, 55.9578555)),
                usesMoonsighting: false)
        case .moonsighting:
            return MethodDescriptor(
                code: "MOONSIGHTING",
                methodName: "Moonsighting Committee Worldwide (Moonsighting.com)",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 18.0, adjustments: MethodAdjustments(dhuhr: 5, maghrib: 3)),
                usesMoonsighting: true)
        case .dubai:
            return MethodDescriptor(
                code: "DUBAI",
                methodName: "The Gulf Region — Dubai",
                params: MethodParams(fajrAngle: 18.2, ishaAngle: 18.2, adjustments: MethodAdjustments(sunrise: -3, dhuhr: 3, asr: 3, maghrib: 3), location: Coordinates(25.0762677, 55.087404)),
                usesMoonsighting: false)
        case .jakim:
            return MethodDescriptor(
                code: "JAKIM",
                methodName: "Jabatan Kemajuan Islam Malaysia (JAKIM)",
                params: MethodParams(fajrAngle: 20.0, ishaAngle: 18.0, location: Coordinates(3.139003, 101.686855)),
                usesMoonsighting: false)
        case .tunisia:
            return MethodDescriptor(
                code: "TUNISIA",
                methodName: "Tunisia",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 18.0, location: Coordinates(36.8064948, 10.1815316)),
                usesMoonsighting: false)
        case .algeria:
            return MethodDescriptor(
                code: "ALGERIA",
                methodName: "Algeria",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.0, location: Coordinates(36.753768, 3.0587561)),
                usesMoonsighting: false)
        case .kemenag:
            return MethodDescriptor(
                code: "KEMENAG",
                methodName: "Kementerian Agama Republik Indonesia",
                params: MethodParams(fajrAngle: 20.0, ishaAngle: 18.0, location: Coordinates(-6.2087634, 106.845599)),
                usesMoonsighting: false)
        case .morocco:
            return MethodDescriptor(
                code: "MOROCCO",
                methodName: "Morocco",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.0, location: Coordinates(33.9715904, -6.8498129)),
                usesMoonsighting: false)
        case .portugal:
            return MethodDescriptor(
                code: "PORTUGAL",
                methodName: "Comunidade Islamica de Lisboa",
                params: MethodParams(fajrAngle: 18.0, ishaMinutesAfterMaghrib: 77, maghribMinutesAfterSunset: 3, location: Coordinates(38.7222524, -9.1393366)),
                usesMoonsighting: false)
        case .jordan:
            return MethodDescriptor(
                code: "JORDAN",
                methodName: "Ministry of Awqaf, Islamic Affairs and Holy Places, Jordan",
                params: MethodParams(fajrAngle: 18.5, ishaMinutesAfterMaghrib: 90, location: Coordinates(31.9461222, 35.923844)),
                usesMoonsighting: false)
        case .oman:
            return MethodDescriptor(
                code: "OMAN",
                methodName: "Ministry of Endowments and Religious Affairs, Oman",
                params: MethodParams(fajrAngle: 18.5, ishaMinutesAfterMaghrib: 90, location: Coordinates(23.588, 58.3829)),
                usesMoonsighting: false)
        case .munich:
            return MethodDescriptor(
                code: "MUNICH",
                methodName: "Islamic Center of Munich, Germany",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.0, location: Coordinates(48.1351, 11.582)),
                usesMoonsighting: false)
        case .maldives:
            return MethodDescriptor(
                code: "MALDIVES",
                methodName: "Ministry of Islamic Affairs, Maldives",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.0, location: Coordinates(4.1755, 73.5093)),
                usesMoonsighting: false)
        case .canada:
            return MethodDescriptor(
                code: "CANADA",
                methodName: "Canada",
                params: MethodParams(fajrAngle: 15.0, ishaAngle: 15.0, location: Coordinates(45.4215, -75.6972)),
                usesMoonsighting: false)
        case .tajikistan:
            return MethodDescriptor(
                code: "TAJIKISTAN",
                methodName: "Islamic Center of Tajikistan",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.0, location: Coordinates(38.5598, 68.787)),
                usesMoonsighting: false)
        case .vienna:
            return MethodDescriptor(
                code: "VIENNA",
                methodName: "Islamic Community of Austria, Vienna",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.0, location: Coordinates(48.2082, 16.3738)),
                usesMoonsighting: false)
        case .belgium:
            return MethodDescriptor(
                code: "BELGIUM",
                methodName: "Belgium",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.0, location: Coordinates(50.8503, 4.3517)),
                usesMoonsighting: false)
        case .sudan:
            return MethodDescriptor(
                code: "SUDAN",
                methodName: "Sudan",
                params: MethodParams(fajrAngle: 19.5, ishaAngle: 17.5, location: Coordinates(15.5007, 32.5599)),
                usesMoonsighting: false)
        case .libya:
            return MethodDescriptor(
                code: "LIBYA",
                methodName: "Libya",
                params: MethodParams(fajrAngle: 19.5, ishaAngle: 17.5, location: Coordinates(32.8872, 13.1913)),
                usesMoonsighting: false)
        case .iraq:
            return MethodDescriptor(
                code: "IRAQ",
                methodName: "Iraq",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.0, location: Coordinates(33.3152, 44.3661)),
                usesMoonsighting: false)
        case .luxembourg:
            return MethodDescriptor(
                code: "LUXEMBOURG",
                methodName: "Luxembourg",
                params: MethodParams(fajrAngle: 18.0, ishaAngle: 17.0, location: Coordinates(49.6116, 6.1319)),
                usesMoonsighting: false)
        case .custom:
            return MethodDescriptor(
                code: "CUSTOM",
                methodName: "Custom",
                params: MethodParams(fajrAngle: 15.0, ishaAngle: 15.0),
                usesMoonsighting: false)
        }
    }
}

/// The per-method data behind `CalculationMethod`'s computed properties.
struct MethodDescriptor: Sendable {
    let code: String
    let methodName: String
    let params: MethodParams
    let usesMoonsighting: Bool
}
