// Generated by islamic_kit_plus tool/generate_native_data.dart — DO NOT EDIT.
// Regenerate from the Dart package; every literal here mirrors the Dart source.

// End-user localization (title + description) for every enum except
// `CalculationMethod`, which carries its own.

extension AsrSchool {
    /// Short UI label for `language`.
    public func title(_ language: Language) -> String {
        switch self {
        case .standard: return language == .ar ? "القياسي (الشافعي والمالكي والحنبلي)" : "Standard (Shafi'i, Maliki, Hanbali)"
        case .hanafi: return language == .ar ? "الحنفي" : "Hanafi"
        }
    }

    /// One-sentence description for `language`.
    public func description(_ language: Language) -> String {
        switch self {
        case .standard: return language == .ar ? "يبدأ وقت العصر عندما يساوي طول ظل الشيء طوله (معامل الظل 1)." : "Asr begins when an object's shadow equals its own length (shadow factor 1)."
        case .hanafi: return language == .ar ? "يبدأ وقت العصر عندما يبلغ طول ظل الشيء ضعف طوله (معامل الظل 2)." : "Asr begins when an object's shadow is twice its own length (shadow factor 2)."
        }
    }
}

extension MidnightMode {
    /// Short UI label for `language`.
    public func title(_ language: Language) -> String {
        switch self {
        case .standard: return language == .ar ? "القياسي" : "Standard"
        case .jafari: return language == .ar ? "الجعفري (الشيعة)" : "Jafari (Shia)"
        }
    }

    /// One-sentence description for `language`.
    public func description(_ language: Language) -> String {
        switch self {
        case .standard: return language == .ar ? "منتصف الليل هو منتصف المدة بين الغروب وشروق اليوم التالي." : "Midnight is the midpoint between sunset and the following sunrise."
        case .jafari: return language == .ar ? "منتصف الليل هو منتصف المدة بين الغروب وفجر اليوم التالي." : "Midnight is the midpoint between sunset and the following Fajr."
        }
    }
}

extension HighLatitudeRule {
    /// Short UI label for `language`.
    public func title(_ language: Language) -> String {
        switch self {
        case .none: return language == .ar ? "بدون" : "None"
        case .middleOfNight: return language == .ar ? "منتصف الليل" : "Middle of Night"
        case .oneSeventh: return language == .ar ? "سُبع الليل" : "One-Seventh"
        case .angleBased: return language == .ar ? "حسب الزاوية" : "Angle-Based"
        }
    }

    /// One-sentence description for `language`.
    public func description(_ language: Language) -> String {
        switch self {
        case .none: return language == .ar ? "لا يُطبَّق أي تعديل على المواقيت في خطوط العرض العالية." : "No high-latitude adjustment is applied to the twilight times."
        case .middleOfNight: return language == .ar ? "يُقسَّم الليل نصفين ليقيّد وقتي الفجر والعشاء عند منتصف الليل." : "The night is split in half to bound the Fajr and Isha times at its midpoint."
        case .oneSeventh: return language == .ar ? "يُقسَّم الليل إلى سبعة أجزاء لضبط وقتي الفجر والعشاء." : "The night is divided into seven parts to bound the Fajr and Isha times."
        case .angleBased: return language == .ar ? "يُستخدم جزء من الليل يتناسب مع زاوية الشفق (الزاوية ÷ 60)." : "A portion of the night proportional to the twilight angle (angle / 60) is used."
        }
    }
}

extension Shafaq {
    /// Short UI label for `language`.
    public func title(_ language: Language) -> String {
        switch self {
        case .general: return language == .ar ? "عام" : "General"
        case .ahmer: return language == .ar ? "الشفق الأحمر" : "Red Twilight"
        case .abyad: return language == .ar ? "الشفق الأبيض" : "White Twilight"
        }
    }

    /// One-sentence description for `language`.
    public func description(_ language: Language) -> String {
        switch self {
        case .general: return language == .ar ? "الشفق العام الذي يجمع بين الحُمرة والبياض، ويُستخدم لحساب العشاء." : "General twilight, combining the red and white afterglow, used to compute Isha."
        case .ahmer: return language == .ar ? "يُحسب وقت العشاء بناءً على مغيب الشفق الأحمر." : "Isha is based on the disappearance of the red twilight (shafaq al-ahmar)."
        case .abyad: return language == .ar ? "يُحسب وقت العشاء بناءً على مغيب الشفق الأبيض." : "Isha is based on the disappearance of the white twilight (shafaq al-abyad)."
        }
    }
}

extension CalendarMethod {
    /// Short UI label for `language`.
    public func title(_ language: Language) -> String {
        switch self {
        case .hjcosa: return language == .ar ? "الهيئة العليا للقضاء" : "High Judicial Council (KSA)"
        case .uaq: return language == .ar ? "أم القرى" : "Umm al-Qura"
        case .diyanet: return language == .ar ? "ديانت التركية" : "Diyanet (Turkey)"
        case .mathematical: return language == .ar ? "حسابي" : "Mathematical"
        }
    }

    /// One-sentence description for `language`.
    public func description(_ language: Language) -> String {
        switch self {
        case .hjcosa: return language == .ar ? "تقويم أم القرى مع تعديلات الرؤية المعتمدة من الهيئة العليا للقضاء في السعودية (الإعداد الافتراضي)." : "Umm al-Qura calendar with the Saudi High Judicial Council sighting adjustments (aladhan default)."
        case .uaq: return language == .ar ? "تقويم أم القرى الجدولي الرسمي في المملكة العربية السعودية." : "The official Umm al-Qura tabular calendar of Saudi Arabia."
        case .diyanet: return language == .ar ? "التقويم الهجري الجدولي الصادر عن رئاسة الشؤون الدينية التركية (ديانت)." : "The tabular Hijri calendar published by Turkey's Diyanet İşleri Başkanlığı."
        case .mathematical: return language == .ar ? "تقويم هجري حسابي (جدولي) بحت يدعم تعديل الأيام." : "A purely arithmetic (tabular) Hijri calendar that supports a day adjustment."
        }
    }
}

extension TimeFormat {
    /// Short UI label for `language`.
    public func title(_ language: Language) -> String {
        switch self {
        case .h24: return language == .ar ? "24 ساعة" : "24-Hour"
        case .h12: return language == .ar ? "12 ساعة" : "12-Hour"
        case .h12NoSuffix: return language == .ar ? "12 ساعة بدون لاحقة" : "12-Hour (No Suffix)"
        case .float: return language == .ar ? "ساعات عشرية" : "Decimal Hours"
        case .iso8601: return language == .ar ? "آيزو 8601" : "ISO 8601"
        }
    }

    /// One-sentence description for `language`.
    public func description(_ language: Language) -> String {
        switch self {
        case .h24: return language == .ar ? "نظام 24 ساعة، مثل 03:57." : "24-hour clock, e.g. 03:57."
        case .h12: return language == .ar ? "نظام 12 ساعة مع لاحقة ص/م، مثل 3:57 ص." : "12-hour clock with an am/pm suffix, e.g. 3:57 am."
        case .h12NoSuffix: return language == .ar ? "نظام 12 ساعة بدون لاحقة ص/م، مثل 3:57." : "12-hour clock without an am/pm suffix, e.g. 3:57."
        case .float: return language == .ar ? "ساعات عشرية خام من 0 إلى 24، مثل 3.95." : "Raw floating-point hours from 0 to 24, e.g. 3.95."
        case .iso8601: return language == .ar ? "طابع زمني بصيغة آيزو 8601 مع إزاحة المنطقة الزمنية، مثل 2014-04-24T03:57:00+01:00." : "ISO-8601 timestamp with a timezone offset, e.g. 2014-04-24T03:57:00+01:00."
        }
    }
}

extension Prayer {
    /// Short UI label for `language`.
    public func title(_ language: Language) -> String {
        switch self {
        case .imsak: return language == .ar ? "الإمساك" : "Imsak"
        case .fajr: return language == .ar ? "الفجر" : "Fajr"
        case .sunrise: return language == .ar ? "الشروق" : "Sunrise"
        case .dhuhr: return language == .ar ? "الظهر" : "Dhuhr"
        case .asr: return language == .ar ? "العصر" : "Asr"
        case .sunset: return language == .ar ? "الغروب" : "Sunset"
        case .maghrib: return language == .ar ? "المغرب" : "Maghrib"
        case .isha: return language == .ar ? "العشاء" : "Isha"
        case .midnight: return language == .ar ? "منتصف الليل" : "Midnight"
        case .firstThird: return language == .ar ? "الثلث الأول" : "First Third"
        case .lastThird: return language == .ar ? "الثلث الأخير" : "Last Third"
        }
    }

    /// One-sentence description for `language`.
    public func description(_ language: Language) -> String {
        switch self {
        case .imsak: return language == .ar ? "وقت الإمساك عن الطعام قبل الفجر أثناء الصيام." : "The time to stop eating before Fajr while fasting."
        case .fajr: return language == .ar ? "صلاة الفجر التي تُؤدَّى قبل شروق الشمس." : "The dawn prayer, observed before sunrise."
        case .sunrise: return language == .ar ? "لحظة شروق الشمس التي تنتهي عندها فترة صلاة الفجر." : "The moment the sun rises, marking the end of the Fajr window."
        case .dhuhr: return language == .ar ? "صلاة الظهر التي تُؤدَّى بعد زوال الشمس عن كبد السماء." : "The noon prayer, observed just after the sun passes its zenith."
        case .asr: return language == .ar ? "صلاة العصر في فترة ما بعد الظهر." : "The afternoon prayer."
        case .sunset: return language == .ar ? "لحظة غروب الشمس التي يبدأ عندها وقت المغرب." : "The moment the sun sets, coinciding with the start of Maghrib."
        case .maghrib: return language == .ar ? "صلاة المغرب التي تُؤدَّى بعد غروب الشمس مباشرة." : "The sunset prayer, observed just after the sun has set."
        case .isha: return language == .ar ? "صلاة العشاء التي تُؤدَّى بعد غياب الشفق." : "The night prayer, observed after twilight has disappeared."
        case .midnight: return language == .ar ? "منتصف الليل الشرعي بين الغروب والفجر." : "The midpoint of the Islamic night."
        case .firstThird: return language == .ar ? "نهاية الثلث الأول من الليل." : "The end of the first third of the night."
        case .lastThird: return language == .ar ? "بداية الثلث الأخير من الليل، وهو وقت مستحب لقيام الليل." : "The start of the last third of the night, favored for night prayer."
        }
    }
}

extension Language {
    /// Short UI label for `language`.
    public func title(_ language: Language) -> String {
        switch self {
        case .en: return language == .ar ? "الإنجليزية" : "English"
        case .ar: return language == .ar ? "العربية" : "Arabic"
        }
    }

    /// One-sentence description for `language`.
    public func description(_ language: Language) -> String {
        switch self {
        case .en: return language == .ar ? "عرض أسماء الصلوات والأشهر وأيام الأسبوع باللغة الإنجليزية." : "Display prayer, month and weekday names in English."
        case .ar: return language == .ar ? "عرض أسماء الصلوات والأشهر وأيام الأسبوع باللغة العربية." : "Display prayer, month and weekday names in Arabic."
        }
    }
}
