// Generated by islamic_kit_plus tool/generate_native_data.dart — DO NOT EDIT.
// Regenerate from the Dart package; every literal here mirrors the Dart source.

/// HJCoSA announced lunar-sighting overrides: Gregorian `dd-mm-yyyy` ->
/// announced Hijri `dd-mm-yyyy`.
enum HijriSightings {
    static let gregorianToHijri: [String: String] = [
        "27-10-2003": "01-09-1424",
        "13-11-2004": "01-10-1425",
        "11-01-2005": "01-12-1425",
        "20-01-2005": "10-12-1425",
        "23-09-2006": "01-09-1427",
        "21-12-2006": "01-12-1427",
        "30-12-2006": "10-12-1427",
        "12-10-2007": "01-10-1428",
        "10-12-2007": "01-12-1428",
        "19-12-2007": "10-12-1428",
        "30-09-2008": "01-10-1429",
        "27-11-2011": "01-09-1433",
        "10-07-2013": "01-09-1434",
        "05-11-2013": "01-01-1435",
        "29-06-2014": "01-09-1435",
        "15-09-2015": "01-12-1436",
        "24-09-2015": "10-12-1436",
        "15-10-2015": "01-01-1437",
        "03-09-2016": "01-12-1437",
        "12-09-2016": "10-12-1437",
        "17-05-2018": "01-09-1439",
        "10-08-2021": "01-01-1443",
    ]

    /// The inverse map (all announced values are distinct).
    static let hijriToGregorian: [String: String] =
        Dictionary(uniqueKeysWithValues: gregorianToHijri.map { ($1, $0) })
}
