// Generated by islamic_kit_plus tool/generate_native_data.dart — DO NOT EDIT.
// Regenerate from the Dart package; every literal here mirrors the Dart source.

/// Islamic holidays keyed by Hijri month, then day.
enum HijriHolidays {
    static let byMonth: [Int: [Int: [String]]] = [
        1: [
            1: ["Birth of Khas Muhammad ash-Shirwani ق"],
            9: ["Urs of Sayyidina Qāsim ibn Muḥammad ibn Abī Bakr ق"],
            10: ["Ashura", "Urs of Shaykh Shamsuddin Habīb Allah ق", "Urs of Shaykh Abū al‑Hassan al‑Kharqāni ق", "Birth of Imam Rābbani Ahmad Al-Fāruqi As-Sirhindi ق"],
            14: ["Birth of Khwaja Bahauddin Shah Naqshband ق"],
            16: ["Birth of Shaykh Jamaluddin al-Ghumuqi al-Husayni ق"],
            17: ["Urs of Shaykh Muhammad Effendi al‑Yaraghi ق"],
            19: ["Urs of Shaykh Darwish Muhammad ق"],
            25: ["Urs of Sayyidina Ali ibn Zayn al-Abidin ق"],
        ],
        2: [
            1: ["End of the holy months"],
            5: ["Urs of Shaykh Yaʿqub al-Charkhi (ق)"],
            12: ["Urs of Shaykh Abdullah Dahlawi (ق)"],
            17: ["Urs of Imam Rabbani Ahmad al-Faruqi as-Sirhindi (ق)"],
            28: ["Martyrdom of Sayyidina al-Hassan al-Mujtaba (ر)"],
        ],
        3: [
            3: ["Urs of Shaykh Bahaʾuddin Shah Naqshband ق"],
            6: ["Birth of Mawlāna Jalāluddīn Rūmi ق"],
            9: ["Urs of Shaykh Muhammad al-Masūm ق"],
            12: ["Mawlid (Birth) al-Nabi ﷺ", "Veiling of the Prophet Muhammad ﷺ", "Birth of Mawlana Shaykh Abdullāh al Dāghestāni ق", "Urs of Shaykh Abu Yāqub Yūsuf al-Hamadāni ق", "Urs of Shaykh Abdul Khāliq al-Ghujdawāni ق", "Urs of Mawlāna Ubaydullaāh Ahrār ق", "Urs of Shaykh Muhammad az-Zāhid ق"],
            17: ["Urs of Shaykh Mahmūd al-Anjir al-Faghnāwi ق", "Urs of Shaykh Abu Ahmad as-Sughūri ق"],
            18: ["Urs of Shaykh Adnān Kabbāni ق"],
        ],
        4: [
            11: ["Urs of Shaykh Abdul Qadir Jilāni ق"],
            14: ["Urs of Imām Abu Hamīd al-Ghazzāli ق"],
            22: ["Urs of Shaykh Muhiyuddīn Ibn al-‘Arabi ق"],
        ],
        5: [
            27: ["Urs of Shaykh Sharafuddīn ad-Daghestāni ق"],
        ],
        6: [
            3: ["Urs of Mawlānā Shaykh Hishām Kabbāni ق"],
            10: ["Urs of Muhammad Bābā as-Samasi ق"],
            14: ["Urs of Muhammad Bāqi Billāh  ق"],
        ],
        7: [
            1: ["Beginning of the holy months"],
            6: ["Urs of Hadhrat Shaykh Moīn al-Dīn Chishti (ق)"],
            8: ["Urs of Mawlāna Shaykh Nāzim al-Haqqāni (ق)"],
            13: ["Birth of Sayyidina `Ali ibn Abi Talib (ر)"],
            15: ["Urs of Sayyidina Jāfar as-Sādiq (ق)", "Urs of Zaynab bint Ali (ر)"],
            27: ["Lailat-ul-Miraj"],
        ],
        8: [
            3: ["Birth of Sayyidina Husayn ibn `Ali (ر)"],
            4: ["Birth of Sayyidina Abbas ibn `Ali (ر)"],
            5: ["Birth of Sayyidina `Ali ibn Husayn (ر)", "Urs of Imam Shamil al-Daghestani (ق)"],
            7: ["Birth of Sayyidina Qasim ibn Hasan (ر)"],
            11: ["Birth of Sayyidina Ali Akbar ibn Husayn (ر)"],
            15: ["Lailat-ul-Bara'at", "Urs of Sayyidina Abu Yazid al-Bistami (ق)"],
            22: ["Urs of Muhammad Usman Damani (ق)"],
        ],
        9: [
            1: ["1st Day of Ramadan"],
            21: ["Lailat-ul-Qadr"],
            23: ["Lailat-ul-Qadr"],
            25: ["Lailat-ul-Qadr"],
            27: ["Lailat-ul-Qadr"],
            29: ["Lailat-ul-Qadr"],
        ],
        10: [
            1: ["Eid-ul-Fitr"],
            3: ["Urs of Hajjah Amina Ādil ق", "Birth of Imam Bukhārī (ر)"],
        ],
        11: [
            1: ["Treaty of Hudaybiyya"],
            2: ["Birth of Muhammad Effendi al-Yaraghi (ق) "],
            3: ["Birth of Sharafuddin ad-Daghestani (ق)"],
            7: ["Birth of Ismail Muhammad ash-Shirwani (ق)"],
            13: ["Urs of Khalid al-Baghdadi (ق)"],
            18: ["Urs of Ali ar-Ramitani (ق)"],
        ],
        12: [
            8: ["Hajj"],
            9: ["Hajj", "Arafa"],
            10: ["Eid-ul-Adha", "Hajj", "Urs Ismail Muhammad ash-Shirwani ق"],
            11: ["Hajj", "Urs of Uthman ibn Affan (3rd Caliph) (ر)"],
            12: ["Hajj"],
            13: ["Hajj"],
            19: ["First time Adhan was called in 622 AD"],
        ],
    ]
}
