#!/usr/bin/env bash
# Copies the conformance fixtures generated by the Dart package into this
# repo's test resources. Regenerate them first in islamic_kit_plus with:
#   TZ=UTC dart run tool/conformance/generate.dart conformance
set -euo pipefail
here="$(cd "$(dirname "$0")/.." && pwd)"
src="${1:-$here/../islamic_kit_plus/conformance}"
core="$here/Tests/IslamicKitPlusTests/Fixtures/conformance"
geo="$here/Tests/IslamicKitPlusGeocodingTests/Fixtures/conformance"
[ -f "$src/manifest.json" ] || { echo "no fixtures at $src" >&2; exit 1; }
mkdir -p "$core" "$geo"
for f in manifest timings_matrix timings_detail hijri qibla next_prayer calendars methods aladhan localization moonsighting geocoder_curated; do
  cp "$src/$f.json" "$core/$f.json"
done
for f in manifest geocoder_sqlite directory; do
  cp "$src/$f.json" "$geo/$f.json"
done
echo "synced fixtures from $src (generator $(python3 -c "import json;print(json.load(open('$src/manifest.json'))['gitSha'][:12])"))"
